repos:
-   repo: https://github.com/Zt0/ai_commit_generator
    rev: v1.0.0
    hooks:
    -   id: ai-commit-generator
        name: Generate Commit Message
        entry: python -m main.py  # Ensure the script runs
        language: system
        args: []
        stages: [prepare-commit-msg]
        pass_filenames: true
        always_run: true
        files: ".*"  # Run on all file types
